//
//  GureumComposer.h
//  CharmIM
//
//  Created by youknowone on 11. 9. 16..
//  Copyright 2011 youknowone.org. All rights reserved.
//

#import "CIMComposer.h"

FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierQwerty;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierDvorak;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierDvorakQwertyCommand;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierColemak;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierColemakQwertyCommand;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan2;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan2Classic;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3Final;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3FinalLoose;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan390;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan390Loose;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3NoShift;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3Classic;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3Layout2;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHanAhnmatae;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHanRoman;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3_2011;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3_2011Loose;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3_2012;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3_2012Loose;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3_2014;
FOUNDATION_EXTERN NSString *kGureumInputSourceIdentifierHan3_2015;
